# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ruizhi/opencv_ws

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ruizhi/opencv_ws

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ruizhi/opencv_ws/CMakeFiles /home/ruizhi/opencv_ws/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ruizhi/opencv_ws/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Basic_thresholding_op

# Build rule for target.
Basic_thresholding_op: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Basic_thresholding_op
.PHONY : Basic_thresholding_op

# fast build rule for target.
Basic_thresholding_op/fast:
	$(MAKE) -f CMakeFiles/Basic_thresholding_op.dir/build.make CMakeFiles/Basic_thresholding_op.dir/build
.PHONY : Basic_thresholding_op/fast

#=============================================================================
# Target rules for targets named Image-Pyramids

# Build rule for target.
Image-Pyramids: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Image-Pyramids
.PHONY : Image-Pyramids

# fast build rule for target.
Image-Pyramids/fast:
	$(MAKE) -f CMakeFiles/Image-Pyramids.dir/build.make CMakeFiles/Image-Pyramids.dir/build
.PHONY : Image-Pyramids/fast

#=============================================================================
# Target rules for targets named Morphology_tf

# Build rule for target.
Morphology_tf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Morphology_tf
.PHONY : Morphology_tf

# fast build rule for target.
Morphology_tf/fast:
	$(MAKE) -f CMakeFiles/Morphology_tf.dir/build.make CMakeFiles/Morphology_tf.dir/build
.PHONY : Morphology_tf/fast

#=============================================================================
# Target rules for targets named DisplayImage

# Build rule for target.
DisplayImage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DisplayImage
.PHONY : DisplayImage

# fast build rule for target.
DisplayImage/fast:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/build
.PHONY : DisplayImage/fast

#=============================================================================
# Target rules for targets named image

# Build rule for target.
image: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 image
.PHONY : image

# fast build rule for target.
image/fast:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/build
.PHONY : image/fast

#=============================================================================
# Target rules for targets named Grayimage

# Build rule for target.
Grayimage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Grayimage
.PHONY : Grayimage

# fast build rule for target.
Grayimage/fast:
	$(MAKE) -f CMakeFiles/Grayimage.dir/build.make CMakeFiles/Grayimage.dir/build
.PHONY : Grayimage/fast

#=============================================================================
# Target rules for targets named ErodingandDilating

# Build rule for target.
ErodingandDilating: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ErodingandDilating
.PHONY : ErodingandDilating

# fast build rule for target.
ErodingandDilating/fast:
	$(MAKE) -f CMakeFiles/ErodingandDilating.dir/build.make CMakeFiles/ErodingandDilating.dir/build
.PHONY : ErodingandDilating/fast

Basic_thresholding_op.o: Basic_thresholding_op.cpp.o

.PHONY : Basic_thresholding_op.o

# target to build an object file
Basic_thresholding_op.cpp.o:
	$(MAKE) -f CMakeFiles/Basic_thresholding_op.dir/build.make CMakeFiles/Basic_thresholding_op.dir/Basic_thresholding_op.cpp.o
.PHONY : Basic_thresholding_op.cpp.o

Basic_thresholding_op.i: Basic_thresholding_op.cpp.i

.PHONY : Basic_thresholding_op.i

# target to preprocess a source file
Basic_thresholding_op.cpp.i:
	$(MAKE) -f CMakeFiles/Basic_thresholding_op.dir/build.make CMakeFiles/Basic_thresholding_op.dir/Basic_thresholding_op.cpp.i
.PHONY : Basic_thresholding_op.cpp.i

Basic_thresholding_op.s: Basic_thresholding_op.cpp.s

.PHONY : Basic_thresholding_op.s

# target to generate assembly for a file
Basic_thresholding_op.cpp.s:
	$(MAKE) -f CMakeFiles/Basic_thresholding_op.dir/build.make CMakeFiles/Basic_thresholding_op.dir/Basic_thresholding_op.cpp.s
.PHONY : Basic_thresholding_op.cpp.s

DisplayImage.o: DisplayImage.cpp.o

.PHONY : DisplayImage.o

# target to build an object file
DisplayImage.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/DisplayImage.cpp.o
.PHONY : DisplayImage.cpp.o

DisplayImage.i: DisplayImage.cpp.i

.PHONY : DisplayImage.i

# target to preprocess a source file
DisplayImage.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/DisplayImage.cpp.i
.PHONY : DisplayImage.cpp.i

DisplayImage.s: DisplayImage.cpp.s

.PHONY : DisplayImage.s

# target to generate assembly for a file
DisplayImage.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/DisplayImage.cpp.s
.PHONY : DisplayImage.cpp.s

ErodingandDilating.o: ErodingandDilating.cpp.o

.PHONY : ErodingandDilating.o

# target to build an object file
ErodingandDilating.cpp.o:
	$(MAKE) -f CMakeFiles/ErodingandDilating.dir/build.make CMakeFiles/ErodingandDilating.dir/ErodingandDilating.cpp.o
.PHONY : ErodingandDilating.cpp.o

ErodingandDilating.i: ErodingandDilating.cpp.i

.PHONY : ErodingandDilating.i

# target to preprocess a source file
ErodingandDilating.cpp.i:
	$(MAKE) -f CMakeFiles/ErodingandDilating.dir/build.make CMakeFiles/ErodingandDilating.dir/ErodingandDilating.cpp.i
.PHONY : ErodingandDilating.cpp.i

ErodingandDilating.s: ErodingandDilating.cpp.s

.PHONY : ErodingandDilating.s

# target to generate assembly for a file
ErodingandDilating.cpp.s:
	$(MAKE) -f CMakeFiles/ErodingandDilating.dir/build.make CMakeFiles/ErodingandDilating.dir/ErodingandDilating.cpp.s
.PHONY : ErodingandDilating.cpp.s

Grayimage.o: Grayimage.cpp.o

.PHONY : Grayimage.o

# target to build an object file
Grayimage.cpp.o:
	$(MAKE) -f CMakeFiles/Grayimage.dir/build.make CMakeFiles/Grayimage.dir/Grayimage.cpp.o
.PHONY : Grayimage.cpp.o

Grayimage.i: Grayimage.cpp.i

.PHONY : Grayimage.i

# target to preprocess a source file
Grayimage.cpp.i:
	$(MAKE) -f CMakeFiles/Grayimage.dir/build.make CMakeFiles/Grayimage.dir/Grayimage.cpp.i
.PHONY : Grayimage.cpp.i

Grayimage.s: Grayimage.cpp.s

.PHONY : Grayimage.s

# target to generate assembly for a file
Grayimage.cpp.s:
	$(MAKE) -f CMakeFiles/Grayimage.dir/build.make CMakeFiles/Grayimage.dir/Grayimage.cpp.s
.PHONY : Grayimage.cpp.s

Image-Pyramids.o: Image-Pyramids.cpp.o

.PHONY : Image-Pyramids.o

# target to build an object file
Image-Pyramids.cpp.o:
	$(MAKE) -f CMakeFiles/Image-Pyramids.dir/build.make CMakeFiles/Image-Pyramids.dir/Image-Pyramids.cpp.o
.PHONY : Image-Pyramids.cpp.o

Image-Pyramids.i: Image-Pyramids.cpp.i

.PHONY : Image-Pyramids.i

# target to preprocess a source file
Image-Pyramids.cpp.i:
	$(MAKE) -f CMakeFiles/Image-Pyramids.dir/build.make CMakeFiles/Image-Pyramids.dir/Image-Pyramids.cpp.i
.PHONY : Image-Pyramids.cpp.i

Image-Pyramids.s: Image-Pyramids.cpp.s

.PHONY : Image-Pyramids.s

# target to generate assembly for a file
Image-Pyramids.cpp.s:
	$(MAKE) -f CMakeFiles/Image-Pyramids.dir/build.make CMakeFiles/Image-Pyramids.dir/Image-Pyramids.cpp.s
.PHONY : Image-Pyramids.cpp.s

Morphology_tf.o: Morphology_tf.cpp.o

.PHONY : Morphology_tf.o

# target to build an object file
Morphology_tf.cpp.o:
	$(MAKE) -f CMakeFiles/Morphology_tf.dir/build.make CMakeFiles/Morphology_tf.dir/Morphology_tf.cpp.o
.PHONY : Morphology_tf.cpp.o

Morphology_tf.i: Morphology_tf.cpp.i

.PHONY : Morphology_tf.i

# target to preprocess a source file
Morphology_tf.cpp.i:
	$(MAKE) -f CMakeFiles/Morphology_tf.dir/build.make CMakeFiles/Morphology_tf.dir/Morphology_tf.cpp.i
.PHONY : Morphology_tf.cpp.i

Morphology_tf.s: Morphology_tf.cpp.s

.PHONY : Morphology_tf.s

# target to generate assembly for a file
Morphology_tf.cpp.s:
	$(MAKE) -f CMakeFiles/Morphology_tf.dir/build.make CMakeFiles/Morphology_tf.dir/Morphology_tf.cpp.s
.PHONY : Morphology_tf.cpp.s

image.o: image.cpp.o

.PHONY : image.o

# target to build an object file
image.cpp.o:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/image.cpp.o
.PHONY : image.cpp.o

image.i: image.cpp.i

.PHONY : image.i

# target to preprocess a source file
image.cpp.i:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/image.cpp.i
.PHONY : image.cpp.i

image.s: image.cpp.s

.PHONY : image.s

# target to generate assembly for a file
image.cpp.s:
	$(MAKE) -f CMakeFiles/image.dir/build.make CMakeFiles/image.dir/image.cpp.s
.PHONY : image.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Basic_thresholding_op"
	@echo "... Image-Pyramids"
	@echo "... edit_cache"
	@echo "... Morphology_tf"
	@echo "... DisplayImage"
	@echo "... rebuild_cache"
	@echo "... image"
	@echo "... Grayimage"
	@echo "... ErodingandDilating"
	@echo "... Basic_thresholding_op.o"
	@echo "... Basic_thresholding_op.i"
	@echo "... Basic_thresholding_op.s"
	@echo "... DisplayImage.o"
	@echo "... DisplayImage.i"
	@echo "... DisplayImage.s"
	@echo "... ErodingandDilating.o"
	@echo "... ErodingandDilating.i"
	@echo "... ErodingandDilating.s"
	@echo "... Grayimage.o"
	@echo "... Grayimage.i"
	@echo "... Grayimage.s"
	@echo "... Image-Pyramids.o"
	@echo "... Image-Pyramids.i"
	@echo "... Image-Pyramids.s"
	@echo "... Morphology_tf.o"
	@echo "... Morphology_tf.i"
	@echo "... Morphology_tf.s"
	@echo "... image.o"
	@echo "... image.i"
	@echo "... image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

